version: '3.8'

services:
  backend:
    image: qhtsg/netflix-backend
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    image: qhtsg/netflix-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMDB_V3_API_KEY: ${TMDB_V3_API_KEY}
