apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml
- pvc.yml
- secrets.yml

images:
- name: qhtsg/netflix-backend
  newTag: "23"
- name: qhtsg/netflix-frontend
  newTag: "23"
