apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: frontend=qhtsg/netflix-frontend,backend=qhtsg/netflix-backend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^[0-9]+$
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[0-9]+$
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-repo: https://github.com/qht-nice/netflix-clone-devsecops.git
    argocd-image-updater.argoproj.io/pull-secret: pullsecret:argocd/argocd-image-updater-secret
    argocd-image-updater.argoproj.io/backend.update-init-containers: "true"
    argocd-image-updater.argoproj.io/ignore: postgres
spec:
  project: default
  source:
    repoURL: https://github.com/qht-nice/netflix-clone-devsecops.git
    targetRevision: main
    path: Kubernetes
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

