apiVersion: v1
kind: Service
metadata:
  name: netflix-postgres
  namespace: default
  labels:
    app: netflix-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: netflix-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-backend
  namespace: default
  labels:
    app: netflix-backend
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30008
  selector:
    app: netflix-backend
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-frontend
  namespace: default
  labels:
    app: netflix-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: netflix-frontend
